TENANT=$(echo "$TENANT" | tr 'A-Z' 'a-z')
PLATFORM=arcsight
NUM_WORKER=3

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_USER=${REDIS_USER}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_GROUP=bif_ncs_alert11

DB_HOST=postgres
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

# SOAR
SOAR_URL=${SOAR_URL}
SOAR_SECRET_KEY=${SOAR_SECRET_KEY}
SOAR_ACCESS_ID=${SOAR_ACCESS_ID}


# Arcsight
ARCSIGHT_URL=${SIEM_URL}
ARCSIGHT_USERNAME=${SIEM_USER}
ARCSIGHT_PASSWORD=${SIEM_PASSWORD}
ARCSIGHT_QUERY_VIEWERS=${ARCSIGHT_QUERY_VIEWERS}