#!/bin/bash

cat > .env.pt <<EOF
TENANT = $(echo "$TENANT" | tr 'A-Z' 'a-z')
PLATFORM=pt
NUM_WORKER=3
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_USER=${REDIS_USER}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_GROUP=bif_ncs_alert11
DB_HOST=postgres
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
# SOAR
SOAR_URL=${SOAR_URL}
# SOAR_SECRET_KEY=your_soar_secret_key
# SOAR_ACCESS_ID=your_soar_access_id
SOAR_TOKEN=${SOAR_SIEM_TOKEN}
PT_URL=${SIEM_URL}
PT_USER=${SIEM_USER}
PT_PASSWORD=${SIEM_PASSWORD}
PT_CLIENT_SECRET=${PT_CLIENT_SECRET}
EOF