#!/bin/bash

cat > .env.pt <<EOF
TENANT = $(echo "$TENANT" | tr 'A-Z' 'a-z')
PLATFORM=pt
NUM_WORKER=3
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_USER=${REDIS_USER}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_GROUP=bif_ncs_alert11
DB_HOST=postgres
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
# SOAR
SOAR_URL=${SOAR_URL}
SOAR_TOKEN=${SOAR_SIEM_TOKEN}
# SIEM
SIEM_URL=${SIEM_URL}
SIEM_TOKEN=${SIEM_API_KEY}
EOF